CREATE TABLE animals (
    ID INT GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    ESCAPE_ATTEMPTS INT NOT NULL,
    NEUTERED BOOLEAN NOT NULL,
    WEIGHT_KG DECIMAL NOT NULL
    PRIMARY KEY (ID)
);
ALTER TABLE animals 
ADD COLUMN species VARCHAR;

CREATE TABLE owners (
    id INT GENERATED ALWAYS AS IDENTITY,
    full_name VARCHAR NOT NULL,
    age INT,
    PRIMARY KEY (id)
);
CREATE TABLE species (
    id INT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR NOT NULL,
    PRIMARY KEY (id)
);
ALTER TABLE animals
DROP COLUMN species;

ALTER TABLE animals 
ADD COLUMN species_id INT;

ALTER TABLE animals
ADD CONSTRAINT fk_species FOREIGN KEY (species_id) REFERENCES species(id);

ALTER TABLE animals 
ADD COLUMN owner_id INT;

ALTER TABLE animals
ADD CONSTRAINT fk_owner
FOREIGN KEY (owner_id)
REFERENCES owners(id);



CREATE TABLE vets  (
    ID INT GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR NOT NULL,
    AGE INT NOT NULL,
    DATE_OF_GRADUATION DATE NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE specializations (
    SPECIES_ID INT NOT NULL,
    VET_ID INT NOT NULL,
    PRIMARY KEY(SPECIES_ID,VET_ID) ,
    FOREIGN KEY (SPECIES_ID) REFERENCES species(id),
    FOREIGN KEY (VET_ID) REFERENCES vets(id)
);

CREATE TABLE visits (
    VET_ID INT NOT NULL,
    ANIMAL_ID INT NOT NULL,
    PRIMARY KEY (VET_ID,ANIMAL_ID),
    FOREIGN KEY (VET_ID) REFERENCES vets(id),
    FOREIGN KEY (ANIMAL_ID) REFERENCES animals(id)
);

ALTER TABLE visits
ADD COLUMN VISIT_DATE DATE;